# Project info
site_name: IBM Cloud Sample Level 3 
site_description: IBM Cloud Sample Level 3 
site_author: Andrew R. Jones (andrewj@us.ibm.com)
copyright: Copyright &copy; 2024 IBM

# Repository
repo_name: IBM/SalesEnablement-test-repo2
#repo_url: https://github.com/IBM/SalesEnablement-L3-test-repo2
#edit_uri: edit/master/docs
docs_dir: docs

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - content.code.annotate
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

plugins:
    - mkdocs-video
    - macros
    - search

markdown_extensions:
  - sane_lists
  - pymdownx.details
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - attr_list
  - md_in_html

nav:
  - Introduction: 'index.md'
  - Part 1 - Overview:
    - 'Introduction': 'Part 1/01 Introduction.md'
    - 'Reserve the environment': 'Part 1/02 Reserve.md'
  - Part 2 - Provisioning a PowerVS workspace:
    - 'Introduction': 'Part 2/01 Introduction.md'
    - 'Click through demonstration of a workspace being provisioned': 'Part 2/02 Clickthru-service.md'
  - Part 3 - Next steps:
    - 'Next steps': 'Part 3/01 Next steps.md'

extra:
  generator: false
  supportEmail: "andrewj@us.ibm.com"
  supportSlack: 
    name: "#cloud-platform-demo-feedback"
    url: "https://ibm-technology-sales.slack.com/archives/C03PQ47KRQE"
  learningplan:
    name: "IBM Power Virtual Server for Technical Sales - Level 3"
    url: "https://yourlearning.ibm.com/activity/PLAN-7D757C8B58E7"
  offering:
    name1: "IBM Power Virtual Server"
  guide:
    name: "IBM Power Virtual Server - Level 3 Demonstration Guide"
    url: "https://ibm.github.io/SalesEnablement-PowerVS-L3/"
  tz_environment:
    name: "IBM Power Virtual Server - Sales Enablment L3"
    url: "https://techzone.ibm.com/my/reservations"
  account: "2305900 - ITZ - ADHOC03"
  powerVS:
    serviceInstanceName: "PowerVS-L3-2024"
    serviceInstanceRG: "PowerVS-L3"
    serviceInstanceLocation: "WDC07"
    placementGroup1: "GroupTogether"
    placementGroup2: "GroupApart"
    sshKey: "PowerVS-key"
    privateSubnet: "private-powervs-2024"
    privateSubnetCIDR: "192.168.100.0/24"
    privateSubnetGW: "192.168.100.15"
    privateSubnetDNS: "127.0.0.1"
    publicSubnet: "public-192_168_222_192-29-VLAN_2056
"
    monitoringInstance: "PowerVS-L3-Monitoring"
    atInstance: "AT-PowerVS-L3"
  aixServer1:
    name: "AIX-VM"
    privateIP: "192.168.100.112"
    publicIP: "150.239.207.227"
    additionalVolumeName: "aix-av1"
  linuxServer1:
    name: "Linux-VM"
    privateIP: "192.168.100.173"
    publicIP: "150.239.207.226"
    additionalVolumeName: "linux-av1"
  ibmiServer1:
    name: "IBMi-VM"
    privateIP: "192.168.100.157"
    publicIP: "150.239.207.228"
    additionalVolumeName: "ibmi-av1"